### ISSUE TITLE
Bug: Face detection algorithm fails to capture face

### ISSUE THREAD

**Issue by rajatrc1705** [rajatrc1705/Emotion-Detection#1]
After the website launches, when trying to access dashboard feature, the camera feature fails to load, throwing the following error.
```
System check identified no issues (0 silenced).
January 21, 2022 - 16:33:23
Django version 3.2.5, using settings 'auth.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Jan/2022 16:33:29] "GET /dashboard/ HTTP/1.1" 200 5440
Traceback (most recent call last):
  File "/home/rajat/miniconda3/envs/lyproject/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/rajat/miniconda3/envs/lyproject/lib/python3.8/wsgiref/handlers.py", line 183, in finish_response
    for data in self.result:
  File "/home/rajat/Dummy/Emotion-Detection/app/login/views.py", line 83, in gen
    frame = camera.get_frame()
  File "/home/rajat/Dummy/Emotion-Detection/app/login/emotion_detection.py", line 39, in get_frame
    faces = faceCascade.detectMultiScale(gray,
cv2.error: OpenCV(4.5.5) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'
```

**Comment by rajatrc1705** [comment]
https://github.com/rajatrc1705/Emotion-Detection/commit/3fc5a162f1ad7b23176765a7a09819f59d6e957a
this commit closes the issue
